load("//javascript/typescript:build_defs.bzl", "ts_library")

package(
    default_applicable_licenses = ["//third_party/hdrscope:license"],
    default_visibility = ["//third_party/hdrscope:__subpackages__"],
)

ts_library(
    name = "color_helpers",
    srcs = [
        "agtm.ts",
        "agtm_adapt.ts",
        "agtm_tone_map_gl.ts",
        "bezier.ts",
        "color_functions.ts",
        "gain_curve.ts",
        "hdr10p.ts",
        "math_helpers.ts",
        "pchip.ts",
        "piecewise_cubic.ts",
        "piecewise_linear.ts",
    ],
)
